# Generated by Django 5.0.6 on 2026-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Display price for this project (optional).', max_digits=10, null=True),
        ),
    ]
