# Generated by Django 5.0.6 on 2026-05-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('popular', 'Popular'), ('hot', 'Hot'), ('new', 'New')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('web', 'Web Development'), ('mobile', 'Mobile'), ('data_science', 'Data Science'), ('ai_ml', 'AI/ML'), ('desktop', 'Desktop'), ('iot', 'IoT'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="e.g. '3 days', 'Instant download'", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube URL or direct .mp4 link', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='List of key feature strings'),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original / crossed-out price (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_links',
            field=models.JSONField(blank=True, default=list, help_text='List of {type, url} dicts'),
        ),
        migrations.AddField(
            model_name='project',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price (₹)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list, help_text='List of technology/tag strings'),
        ),
        migrations.AddField(
            model_name='project',
            name='whats_included',
            field=models.JSONField(blank=True, default=list, help_text="List of 'what's included' strings"),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'URL')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/media/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
